version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - room_service
      - booking_service
      - payment_service
      - auth_service
      - event_service

  room_service:
    build:
      context: ./services/room
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - EVENT_SERVICE_URL=http://event_service:8000
    depends_on:
      - db
      - rabbitmq
      - event_service

  booking_service:
    build:
      context: ./services/booking
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - ROOM_SERVICE_URL=http://room_service:8000
      - PAYMENT_SERVICE_URL=http://payment_service:8000
      - EVENT_SERVICE_URL=http://event_service:8000
    depends_on:
      - db
      - rabbitmq
      - room_service
      - payment_service
      - event_service

  payment_service:
    build:
      context: ./services/payment
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - db
      - rabbitmq

  auth_service:
    build:
      context: ./services/auth
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - rabbitmq

  monitoring_service:
    build:
      context: ./services/monitoring
    ports:
      - "8007:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - db
      - rabbitmq

  event_service:
    build:
      context: ./services/event
    ports:
      - "8006:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - db
      - rabbitmq

  housekeeping_service:
    build:
      context: ./services/housekeeping
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/hotel
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotel
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  kong:
    image: kong:latest
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    depends_on:
      - room_service
      - booking_service
      - payment_service
      - auth_service
      - monitoring_service
      - event_service
      - housekeeping_service

volumes:
  mysql_data: 